# -*- coding: utf-8 -*-

#Textos para pies de foto en anejos y gráficos
capTexts={
    'uX':'desplazamiento en dirección X',
    'uY':'desplazamiento en dirección Y',
    'uZ':'desplazamiento en dirección Z',
    'rotX':"rotación en torno al eje X",
    'rotY':"rotación en torno al eje Y",
    'rotZ':"rotación en torno al eje Z",
    'CF':'factor de capacidad',
    'getCF':'factor de capacidad',
    'N':'esfuerzo normal asociado al factor de capacidad',
    'N1':'esfuerzo normal dirección 1',
    'N2':'esfuerzo normal dirección 2',
    'M1':'momento flector dirección 1',
    'M2':'momento flector dirección 2',
    'Q1':'esfuerzo cortante dirección 1',
    'Q2':'esfuerzo cortante dirección 2',
    'Qy':'esfuerzo cortante dirección y',
    'Qz':'esfuerzo cortante dirección z',
    'My':'momento flector asociado al factor de capacidad',
    'Mz':'momento flector asociado al factor de capacidad',
    'Mu':'valor último del momento flector',
    'theta':'',
    'Vy':'esfuerzo cortante asociado al factor de capacidad',
    'Vz':'esfuerzo cortante asociado al factor de capacidad',
    'Vcu':'',
    'Vsu':'',
    'Vu':"valor último del esfuerzo cortante",
    'LocalAxes': 'ejes locales',
    'FEmesh': 'malla de elementos',
    'ULS_normalStressesResistance': 'Comprobación ELU tensiones normales',
    'normalStressCheck': 'Comprobación ELU tensiones normales',
    'ULS_shearResistance': 'Comprobación ELU esfuerzo cortante',
    'getMaxSteelStress': "tensión máxima en la armadura",
    'SLS_frequentLoadsCrackControl': 'Comprobación ELS fisuración, casos de carga frecuentes',
    'SLS_quasiPermanentLoadsLoadsCrackControl': 'Comprobación ELS fisuración, casos de carga quasi-permanentes',
    
}
