# -*- coding: utf-8 -*-
import def_param_ang_poliedrico

def_param_ang_poliedrico.defParamAngPoliedrico(JP0000)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0001)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0010)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0011)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0100)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0101)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0110)
def_param_ang_poliedrico.defParamAngPoliedrico(JP0111)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1000)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1001)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1010)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1011)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1100)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1101)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1110)
def_param_ang_poliedrico.defParamAngPoliedrico(JP1111)
