# -*- coding: utf-8 -*-
\JP0000{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0001{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0010{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0011{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0100{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0101{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0110{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP0111{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1000{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1001{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1010{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1011{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1100{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1101{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1110{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
\JP1111{execfile(""geotechnics/tuneles/def_param_ang_poliedrico.lcmdi"}")
