#!/bin/sh
# Deletes all the modules previously installed by local_install.sh
# This is done to solve the problem of zombie modules: Python files that has
# been deleted or replaced but which remains installed in the machine.

echo "Uninstalling Debian package."
FILE=./xc_installation_target.txt
if test -f "$FILE"; then
    echo "$FILE exists."
    package_file=$( tail -n 1 $FILE)
    echo "package to uninstall: $package_file"
    sudo dpkg --remove xc-python-modules
else
    echo "No previous package to uninstall."
fi
# Remove precompiled files.
rm -rf build/*
