#!/bin/sh
echo "procesando: " $1
cp -i $1 $1.bak
cat $1.bak  | sed 's/<Graph.h>/"graph\/graph\/Graph.h"/g' \
| sed 's/<GraphNumberer.h>/"graph\/numberer\/GraphNumberer.h"/g' \
| sed 's/<GraphPartitioner.h>/"graph\/partitioner\/GraphPartitioner.h"/g' \
> $1
