from solution import predefined_solutions as ps
ps.solveComb(preprocessor, "ELU001",analysis,numSteps)
procesResultVerif("ELU001)")
ps.solveComb(preprocessor, "ELU002",analysis,numSteps)
procesResultVerif("ELU002)")
ps.solveComb(preprocessor, "ELU003",analysis,numSteps)
procesResultVerif("ELU003)")
ps.solveComb(preprocessor, "ELU004",analysis,numSteps)
procesResultVerif("ELU004)")
ps.solveComb(preprocessor, "ELU005",analysis,numSteps)
procesResultVerif("ELU005)")
ps.solveComb(preprocessor, "ELU006",analysis,numSteps)
procesResultVerif("ELU006)")
ps.solveComb(preprocessor, "ELU007",analysis,numSteps)
procesResultVerif("ELU007)")
ps.solveComb(preprocessor, "ELU008",analysis,numSteps)
procesResultVerif("ELU008)")
ps.solveComb(preprocessor, "ELU009",analysis,numSteps)
procesResultVerif("ELU009)")
ps.solveComb(preprocessor, "ELU010",analysis,numSteps)
procesResultVerif("ELU010)")
ps.solveComb(preprocessor, "ELU011",analysis,numSteps)
procesResultVerif("ELU011)")
ps.solveComb(preprocessor, "ELU012",analysis,numSteps)
procesResultVerif("ELU012)")
ps.solveComb(preprocessor, "ELU013",analysis,numSteps)
procesResultVerif("ELU013)")
ps.solveComb(preprocessor, "ELU014",analysis,numSteps)
procesResultVerif("ELU014)")
ps.solveComb(preprocessor, "ELU015",analysis,numSteps)
procesResultVerif("ELU015)")
ps.solveComb(preprocessor, "ELU016",analysis,numSteps)
procesResultVerif("ELU016)")
ps.solveComb(preprocessor, "ELU017",analysis,numSteps)
procesResultVerif("ELU017)")
ps.solveComb(preprocessor, "ELU018",analysis,numSteps)
procesResultVerif("ELU018)")
ps.solveComb(preprocessor, "ELU019",analysis,numSteps)
procesResultVerif("ELU019)")
ps.solveComb(preprocessor, "ELU020",analysis,numSteps)
procesResultVerif("ELU020)")
ps.solveComb(preprocessor, "ELU021",analysis,numSteps)
procesResultVerif("ELU021)")
ps.solveComb(preprocessor, "ELU022",analysis,numSteps)
procesResultVerif("ELU022)")
ps.solveComb(preprocessor, "ELU023",analysis,numSteps)
procesResultVerif("ELU023)")
ps.solveComb(preprocessor, "ELU024",analysis,numSteps)
procesResultVerif("ELU024)")
ps.solveComb(preprocessor, "ELU025",analysis,numSteps)
procesResultVerif("ELU025)")
ps.solveComb(preprocessor, "ELU026",analysis,numSteps)
procesResultVerif("ELU026)")
