from solution import resuelve_combinacion as rc
rc.resuelveComb(preprocessor, "ELU001",analysis,numSteps)
procesResultVerif("ELU001)")
rc.resuelveComb(preprocessor, "ELU002",analysis,numSteps)
procesResultVerif("ELU002)")
rc.resuelveComb(preprocessor, "ELU003",analysis,numSteps)
procesResultVerif("ELU003)")
rc.resuelveComb(preprocessor, "ELU004",analysis,numSteps)
procesResultVerif("ELU004)")
rc.resuelveComb(preprocessor, "ELU005",analysis,numSteps)
procesResultVerif("ELU005)")
rc.resuelveComb(preprocessor, "ELU006",analysis,numSteps)
procesResultVerif("ELU006)")
rc.resuelveComb(preprocessor, "ELU007",analysis,numSteps)
procesResultVerif("ELU007)")
rc.resuelveComb(preprocessor, "ELU008",analysis,numSteps)
procesResultVerif("ELU008)")
rc.resuelveComb(preprocessor, "ELU009",analysis,numSteps)
procesResultVerif("ELU009)")
rc.resuelveComb(preprocessor, "ELU010",analysis,numSteps)
procesResultVerif("ELU010)")
rc.resuelveComb(preprocessor, "ELU011",analysis,numSteps)
procesResultVerif("ELU011)")
rc.resuelveComb(preprocessor, "ELU012",analysis,numSteps)
procesResultVerif("ELU012)")
rc.resuelveComb(preprocessor, "ELU013",analysis,numSteps)
procesResultVerif("ELU013)")
rc.resuelveComb(preprocessor, "ELU014",analysis,numSteps)
procesResultVerif("ELU014)")
rc.resuelveComb(preprocessor, "ELU015",analysis,numSteps)
procesResultVerif("ELU015)")
rc.resuelveComb(preprocessor, "ELU016",analysis,numSteps)
procesResultVerif("ELU016)")
rc.resuelveComb(preprocessor, "ELU017",analysis,numSteps)
procesResultVerif("ELU017)")
rc.resuelveComb(preprocessor, "ELU018",analysis,numSteps)
procesResultVerif("ELU018)")
rc.resuelveComb(preprocessor, "ELU019",analysis,numSteps)
procesResultVerif("ELU019)")
rc.resuelveComb(preprocessor, "ELU020",analysis,numSteps)
procesResultVerif("ELU020)")
rc.resuelveComb(preprocessor, "ELU021",analysis,numSteps)
procesResultVerif("ELU021)")
rc.resuelveComb(preprocessor, "ELU022",analysis,numSteps)
procesResultVerif("ELU022)")
rc.resuelveComb(preprocessor, "ELU023",analysis,numSteps)
procesResultVerif("ELU023)")
rc.resuelveComb(preprocessor, "ELU024",analysis,numSteps)
procesResultVerif("ELU024)")
rc.resuelveComb(preprocessor, "ELU025",analysis,numSteps)
procesResultVerif("ELU025)")
rc.resuelveComb(preprocessor, "ELU026",analysis,numSteps)
procesResultVerif("ELU026)")
