# Rebar types
A08_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 8e-3, spacing= 0.10, concreteCover= cover)
A10_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 10e-3, spacing= 0.10, concreteCover= cover)
A12_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 12e-3, spacing= 0.10, concreteCover= cover)
A14_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 14e-3, spacing= 0.10, concreteCover= cover)
A16_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 16e-3, spacing= 0.10, concreteCover= cover)
A18_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 18e-3, spacing= 0.10, concreteCover= cover)
A20_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 20e-3, spacing= 0.10, concreteCover= cover)
A22_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 22e-3, spacing= 0.10, concreteCover= cover)
A25_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 25e-3, spacing= 0.10, concreteCover= cover)
A26_10= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 26e-3, spacing= 0.10, concreteCover= cover)

A08_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=8e-3, spacing= 0.15, concreteCover= cover)
A10_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=10e-3, spacing= 0.15, concreteCover= cover)
A12_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=12e-3, spacing= 0.15, concreteCover= cover)
A14_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=14e-3, spacing= 0.15, concreteCover= cover)
A16_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=16e-3, spacing= 0.15, concreteCover= cover)
A18_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=18e-3, spacing= 0.15, concreteCover= cover)
A20_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=20e-3, spacing= 0.15, concreteCover= cover)
A22_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=22e-3, spacing= 0.15, concreteCover= cover)
A25_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=25e-3, spacing= 0.15, concreteCover= cover)
A26_15= SIA262_limit_state_checking.SIARebarFamily(steel= reinfSteel, diam=26e-3, spacing= 0.15, concreteCover= cover)

A08_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 8e-3, spacing= 0.20, concreteCover= cover)
A20_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 10e-3, spacing= 0.20, concreteCover= cover)
A12_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 12e-3, spacing= 0.20, concreteCover= cover)
A14_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 14e-3, spacing= 0.20, concreteCover= cover)
A16_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 16e-3, spacing= 0.20, concreteCover= cover)
A18_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 18e-3, spacing= 0.20, concreteCover= cover)
A20_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 20e-3, spacing= 0.20, concreteCover= cover)
A22_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 22e-3, spacing= 0.20, concreteCover= cover)
A25_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 25e-3, spacing= 0.20, concreteCover= cover)
A26_20= EHE_limit_state_checking.EHERebarFamily(steel= reinfSteel, diam= 26e-3, spacing= 0.20, concreteCover= cover)

