
FIND_LIBRARY(UMFPACK_LIB NAMES umfpack)

SET(UMFPACK_FOUND FALSE)
IF(UMFPACK_LIB)
    SET(UMFPACK_FOUND TRUE)
ENDIF (UMFPACK_LIB)

IF(UMFPACK_FOUND)
    MESSAGE(STATUS "Found Umfpack: ${UMFPACK_LIB}")
ELSE(UMFPACK_FOUND)
    MESSAGE(FATAL_ERROR "Could not find Umfpack")
ENDIF (UMFPACK_FOUND)



