find_package(X11 REQUIRED)
find_package(OpenGL REQUIRED)
find_package(VTK)
find_package(GTK2)
find_package(CGAL REQUIRED COMPONENTS Core)
find_package(GNUGTS REQUIRED)
find_package(CImg REQUIRED)
find_package(MySQL)
find_package(MySQLpp REQUIRED)
find_package(GLIB2)
find_package(PythonInterp)
find_package(PythonLibs REQUIRED)
find_package(Boost 1.45.0)
if(Boost_FOUND)
  INCLUDE_DIRECTORIES("${Boost_INCLUDE_DIRS}" "/usr/include/python2.7")
  SET(Boost_USE_STATIC_LIBS OFF)
  SET(Boost_USE_MULTITHREADED ON)
#  SET(Boost_USE_STATIC_RUNTIME OFF)
  if (${PYTHON_VERSION_MAJOR} EQUAL 3)
    find_package(Boost COMPONENTS system regex filesystem thread python3 REQUIRED)
  else()
    find_package(Boost COMPONENTS system regex filesystem thread python REQUIRED)
  endif()
elseif(NOT Boost_FOUND)
  MESSAGE(FATAL_ERROR "Unable to find correct Boost version. Did you set BOOST_ROOT?")
endif()
find_package(F2C REQUIRED)
find_package(Plot REQUIRED)
find_package(Gnuplot REQUIRED)
find_package(MPFR)
find_package(GMP)
find_package(SQLITE3 REQUIRED)
find_package(MPI)
find_package(Arpack REQUIRED)
find_package(ArpackPP REQUIRED)
find_package(Petsc)
find_package(LAPACK REQUIRED)
find_package(BLAS REQUIRED)
find_package(SuperLU REQUIRED)
find_package(BerkeleyDB REQUIRED)
find_package(METIS REQUIRED)
find_package(TCL REQUIRED)
find_package(MED REQUIRED)
find_package(ORACLE)
