
FIND_LIBRARY(DMUMPS_LIB NAMES dmumps)

SET(DMUMPS_FOUND FALSE)
IF(DMUMPS_LIB)
    SET(DMUMPS_FOUND TRUE)
ENDIF(DMUMPS_LIB)

IF(DMUMPS_FOUND)
    MESSAGE(STATUS "Found DMUMPS: ${DMUMPS_LIB}")
ELSE(DMUMPS_FOUND)
    MESSAGE(FATAL_ERROR "Could not find DMUMPS")
ENDIF(DMUMPS_FOUND)



