# -*- coding: utf-8 -*-
from __future__ import print_function

__author__= "Luis C. Pérez Tato (LCPT) , Ana Ortega (AO_O) "
__copyright__= "Copyright 2026, LCPT, AO_O"
__license__= "GPL"
__version__= "3.0"
__email__= "l.pereztato@ciccp.es, ana.ortega@ciccp.es "


import importlib.resources
import json

en_10210_shapes= dict()

# Data generated by: python_modules/materials/sections/structural_shapes/aux/en_10210-2_en_10219-2/gen_en_10210_rhs_profiles.py

# Section axis: 

#    SCI              XC
#  EN 10210-2

#       ^ Z           ^ Y                    
#       |             |

#     -----         -----
#       |             | 
#       | -> Y        | -> Z
#       |             |
#     -----         -----


# The axis used in the EN 10210-2 standard are different from those used
# in XC (strong axis parallel to z axis) in other words: values for Y
# and Z axis are swapped with respect to those in the catalog.

RHS= None
with importlib.resources.open_text("materials.sections.structural_shapes.aux", "en_10210_rhs_profiles.json") as file:
    RHS= json.load(file)
en_10210_shapes['RHS']= RHS

SHS= None
with importlib.resources.open_text("materials.sections.structural_shapes.aux", "en_10210_shs_profiles.json") as file:
    SHS= json.load(file)
en_10210_shapes['SHS']= SHS

# Circular hollow tubes.
CHS= None
with importlib.resources.open_text("materials.sections.structural_shapes.aux", "en_10210_chs_profiles.json") as file:
    CHS= json.load(file)
en_10210_shapes['CHS']= CHS
